import expected from './fixtures/thesis/text-diff-expected.json';
import versionCurrent from './fixtures/thesis/version-current.json';
import versionPrevious from './fixtures/thesis/version-previous.json';

// ---------------------------------------------------------------------------
// diff-is-of-two-texts — docs/gf-thesis-flows.md T6 :898–:901 ("the text diff, computed by the frontend from two
// immutable texts, and every citation whose pin moved"); docs/gf-ui-flows.md §16 :513–:515, §18 :583–:586, A5 :1070;
// UI plan :401–:402, §5 :911.
//
// THE ONE COMPUTATION THE FRONTEND OWNS, and its whole contract: two texts in, runs out. Its arity is asserted
// because "over exactly two texts" is the clause; its output is asserted against an expected file DERIVED BY HAND
// from the two version fixtures, never generated by the function it checks.
// ---------------------------------------------------------------------------

const textDiff = () => import('../src/lib/textDiff');

const EDGES: readonly (readonly [string, string])[] = [
  ['', ''],
  ['', 'מילה'],
  ['מילה', ''],
  ['אותו טקסט בדיוק', 'אותו טקסט בדיוק'],
  ['  \n  ', '  \n  '],
  ['ראו #ev_0xaa', 'ראו #ev_0xbb'],
  // A pair whose ONLY difference is whitespace: the diff's removed and added runs are blank, and a renderer that
  // dropped them would lose a paragraph break — the losslessness above is what forbids it.
  ['פסקה\n\nשנייה', 'פסקה\nשנייה'],
];

describe('diff-is-of-two-texts', () => {
  it('textDiff takes exactly two texts — before and after, nothing else (T6 :900)', async () => {
    const { textDiff: diff } = await textDiff();
    expect(diff.length).toBe(2);
  });

  it('its runs over the two version fixtures equal the expected diff, derived by hand', async () => {
    const { textDiff: diff } = await textDiff();
    expect(diff(versionPrevious.text, versionCurrent.text)).toEqual(expected.runs);
  });

  it('the runs are lossless: same+removed rejoins the before text, same+added rejoins the after — on the fixtures and on six edge pairs', async () => {
    const { textDiff: diff } = await textDiff();
    const pairs = [[versionPrevious.text, versionCurrent.text] as const, ...EDGES];
    for (const [before, after] of pairs) {
      const runs = diff(before, after);
      const rejoin = (kinds: readonly string[]): string => runs.filter((run) => kinds.includes(run.kind)).map((run) => run.text).join('');
      expect([before, rejoin(['same', 'removed']), rejoin(['same', 'added'])]).toEqual([before, before, after]);
    }
  });

  it('a citation token is ONE unit: a swapped token is one removed run and one added run, never a partial hash', async () => {
    const { textDiff: diff } = await textDiff();
    const runs = diff('ראו #ev_0xaaaa בעמוד', 'ראו #ev_0xbbbb בעמוד');
    expect(runs.map((run) => [run.kind, run.text])).toEqual([
      ['same', 'ראו '],
      ['removed', '#ev_0xaaaa '],
      ['added', '#ev_0xbbbb '],
      ['same', 'בעמוד'],
    ]);
  });

  it('movedPins lists every citation in BOTH versions whose pin differs, in the after version’s order, and nothing else', async () => {
    const { movedPins } = await textDiff();
    expect(movedPins(versionPrevious.citations, versionCurrent.citations)).toEqual(expected.movedPins);
  });
});
